// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAevHyoGo6jfMLKb_uWQ7QqvrzINP7UYFo',
    appId: '1:69321360066:web:84b1f9fa68e7746b48315b',
    messagingSenderId: '69321360066',
    projectId: 'eco365-c6dca',
    authDomain: 'eco365-c6dca.firebaseapp.com',
    storageBucket: 'eco365-c6dca.appspot.com',
    measurementId: 'G-SFLJXE3VSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn5xPUa9J6MTrHW0faWFGfhprFzNEAqjg',
    appId: '1:69321360066:android:d5a8f2d07c2b60d348315b',
    messagingSenderId: '69321360066',
    projectId: 'eco365-c6dca',
    storageBucket: 'eco365-c6dca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvnKI4NPduTik6dfCi6kJ9nMmo0NTAEgs',
    appId: '1:69321360066:ios:74578dcca6a78bca48315b',
    messagingSenderId: '69321360066',
    projectId: 'eco365-c6dca',
    storageBucket: 'eco365-c6dca.appspot.com',
    iosBundleId: 'com.example.localNotificationAppDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvnKI4NPduTik6dfCi6kJ9nMmo0NTAEgs',
    appId: '1:69321360066:ios:74578dcca6a78bca48315b',
    messagingSenderId: '69321360066',
    projectId: 'eco365-c6dca',
    storageBucket: 'eco365-c6dca.appspot.com',
    iosBundleId: 'com.example.localNotificationAppDemo',
  );
}
